export const routes = [
  {
    name: 'Home',
    link: '/',
    isLink: true,
    isDropdown: false,
    dropdownName: '',
    lineHeight: 32,
    dropdown: [],
  },
  {
    name: 'Pages',
    link: '',
    isLink: false,
    isDropdown: true,
    dropdownName: 'pages',
    lineHeight: 32,
    dropdown: [
      {
        link: 'about-us',
        name: 'About Us',
        isLink: true,
        isDropdown: false,
        dropdown: [],
      },
      {
        link: 'our-services',
        name: 'Our Services',
        isLink: true,
        isDropdown: false,
        dropdown: [],
      },
      {
        link: 'contact-us',
        name: 'Contact Us',
        isLink: true,
        isDropdown: false,
        dropdown: [],
      },
    ],
  },
  {
    name: 'Shop',
    link: '/shop',
    isLink: true,
    lineHeight: 32,
    isDropdown: false,
    dropdown: [],
  },
];
