import type { Metadata } from 'next';
import { Rajdhani } from 'next/font/google';
import './globals.css';
import Header from '@/components/common/Header/Header';

const inter = Rajdhani({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} h-screen`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
