import type { Metadata } from 'next';
import { Rajdhani } from 'next/font/google';
import './globals.css';
import { I18nProvider } from '@/lib/i18n/i18n';
import dynamic from 'next/dynamic';
const DynamicHeader = dynamic(
  () => import('@/components/common/Header/Header'),
  { ssr: false }
);
const inter = Rajdhani({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} h-screen`}>
        <I18nProvider>
          <DynamicHeader />
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}
